import type { ComponentProps } from "react";
import {
	Activity,
	Folder,
	FolderOpen,
	Pin,
	PinOff,
	Archive,
	ArrowDown,
	ArrowUp,
	Bell,
	Bookmark,
	CameraOff,
	Check,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	ChevronUp,
	Circle,
	CircleAlert,
	CircleCheck,
	CircleMinus,
	CircleQuestionMark,
	CircleX,
	Clock,
	Cloud,
	CloudDownload,
	Code,
	Command,
	Copy,
	CornerDownLeft,
	CornerDownRight,
	CornerUpRight,
	Cpu,
	Delete,
	Disc,
	Ellipsis,
	ExternalLink,
	Feather as FeatherGlyph,
	File,
	FileText,
	Flag,
	GitBranch,
	GitMerge,
	GitPullRequest,
	Globe,
	Grid2x2,
	Image,
	Inbox,
	Info,
	Italic,
	KeyRound,
	Layers,
	Link,
	List,
	LoaderCircle,
	LogOut,
	Map,
	Maximize,
	Menu,
	MessageCircle,
	MessageSquare,
	Mic,
	MicOff,
	Minus,
	Monitor,
	Moon,
	OctagonX,
	Paperclip,
	Pause,
	Pen,
	PenLine,
	Play,
	Plus,
	Power,
	Radio,
	RefreshCw,
	Repeat,
	RotateCcw,
	RotateCw,
	Save,
	Search,
	Send,
	Server,
	Settings,
	Shield,
	ShieldOff,
	Shuffle,
	SlidersHorizontal,
	Smartphone,
	Square,
	SquareCheck,
	Star,
	Sun,
	Table,
	Terminal,
	Trash,
	TriangleAlert,
	Type,
	Underline,
	User,
	WifiOff,
	Wrench,
	X,
	Zap,
} from "lucide-react-native";

/**
 * The app's icons, drawn from the desktop's set.
 *
 * The renderer draws every icon from Lucide, and this is the same family at the
 * same version — a glyph the desktop shows is the glyph drawn here. Feather was
 * Lucide's ancestor and close enough to pass at a glance, which is exactly how
 * the two products drifted: a chevron with a different shoulder, a lock with a
 * different shackle, one name meaning two drawings.
 *
 * Call sites keep the names they already use, and the map says where Lucide
 * renamed a glyph (`alert-circle` -> `CircleAlert`, `loader` -> `LoaderCircle`)
 * once, here, rather than at forty call sites.
 */
export const glyphs = {
	"activity": Activity,
	"alert-circle": CircleAlert,
	"alert-triangle": TriangleAlert,
	"archive": Archive,
	"arrow-down": ArrowDown,
	"arrow-up": ArrowUp,
	"bell": Bell,
	"bookmark": Bookmark,
	"camera-off": CameraOff,
	"check": Check,
	"check-circle": CircleCheck,
	"check-square": SquareCheck,
	"chevron-down": ChevronDown,
	"chevron-left": ChevronLeft,
	"chevron-right": ChevronRight,
	"chevron-up": ChevronUp,
	"circle": Circle,
	"clock": Clock,
	"cloud": Cloud,
	"code": Code,
	"command": Command,
	"copy": Copy,
	"corner-down-left": CornerDownLeft,
	"corner-down-right": CornerDownRight,
	"corner-up-right": CornerUpRight,
	"cpu": Cpu,
	"delete": Delete,
	"disc": Disc,
	"download-cloud": CloudDownload,
	"edit-2": Pen,
	"edit-3": PenLine,
	"external-link": ExternalLink,
	"feather": FeatherGlyph,
	"file": File,
	"file-text": FileText,
	"folder": Folder,
	"folder-open": FolderOpen,
	"flag": Flag,
	"git-branch": GitBranch,
	"git-merge": GitMerge,
	"git-pull-request": GitPullRequest,
	"globe": Globe,
	"grid": Grid2x2,
	"help-circle": CircleQuestionMark,
	"image": Image,
	"inbox": Inbox,
	"info": Info,
	"italic": Italic,
	"key": KeyRound,
	"layers": Layers,
	"link": Link,
	"list": List,
	"loader": LoaderCircle,
	"log-out": LogOut,
	"map": Map,
	"maximize": Maximize,
	"menu": Menu,
	"message-circle": MessageCircle,
	"message-square": MessageSquare,
	"mic": Mic,
	"mic-off": MicOff,
	"minus": Minus,
	"minus-circle": CircleMinus,
	"monitor": Monitor,
	"moon": Moon,
	"more-horizontal": Ellipsis,
	"paperclip": Paperclip,
	"pin": Pin,
	"pin-off": PinOff,
	"pause": Pause,
	"play": Play,
	"plus": Plus,
	"power": Power,
	"radio": Radio,
	"refresh-cw": RefreshCw,
	"repeat": Repeat,
	"rotate-ccw": RotateCcw,
	"rotate-cw": RotateCw,
	"save": Save,
	"search": Search,
	"send": Send,
	"server": Server,
	"settings": Settings,
	"shield": Shield,
	"shield-off": ShieldOff,
	"shuffle": Shuffle,
	"sliders": SlidersHorizontal,
	"smartphone": Smartphone,
	"square": Square,
	"star": Star,
	"sun": Sun,
	"table": Table,
	"terminal": Terminal,
	"tool": Wrench,
	"trash": Trash,
	"trash-2": Trash,
	"type": Type,
	"underline": Underline,
	"user": User,
	"wifi-off": WifiOff,
	"x": X,
	"x-circle": CircleX,
	"x-octagon": OctagonX,
	"zap": Zap,
} as const;

export type FeatherIconName = keyof typeof glyphs;

/** Feather's calling convention, Lucide's drawings. */
function Icon({
	name,
	size = 24,
	color,
	style,
	...rest
}: {
	/**
	 * A known name autocompletes; a string is accepted because a few call sites
	 * carry an icon name out of data rather than a literal.
	 */
	name: FeatherIconName | (string & {});
	size?: number;
	color?: string;
	style?: ComponentProps<(typeof glyphs)[FeatherIconName]>["style"];
} & Omit<ComponentProps<(typeof glyphs)[FeatherIconName]>, "size" | "color" | "style">) {
	const Glyph = glyphs[name as FeatherIconName];
	if (!Glyph) return null;
	return <Glyph size={size} color={color} style={style} strokeWidth={2} {...rest} />;
}

/**
 * `Feather.glyphMap` is only ever read as a type by call sites that take an icon
 * name in their props; this keeps those signatures working unchanged.
 */
export const Feather = Object.assign(Icon, { glyphMap: {} as Record<string, number> });
