package sessionimport

import "strings"

// Agent CLIs record more than what a person typed. Shell input echoed back,
// caveats prepended to command output, system reminders, hook results, and the
// CLI's own internal requests all land in the transcript as user messages.
//
// Treating one as a prompt has three consequences, all bad: it becomes the
// conversation's title in the sidebar, it becomes the imported session's
// display name, and it is what a classifier is asked to judge. So a turn the
// machine wrote is not counted as a human turn anywhere.

// syntheticPromptPrefixes open a user turn the CLI injected itself.
var syntheticPromptPrefixes = []string{
	// Claude Code.
	"<local-command-caveat>",
	"<command-name>",
	"<command-message>",
	"<command-args>",
	"<local-command-stdout>",
	"<local-command-stderr>",
	"<system-reminder>",
	"<user-prompt-submit-hook>",
	"Caveat: The messages below were generated by the user while running local commands.",
	// Codex: shell input and output are echoed into the conversation.
	"<bash-input>",
	"<bash-output>",
	"<user_instructions>",
	"<environment_context>",
	"<editor_context>",
}

// internalPromptPhrases mark a request the tooling made of the agent rather
// than something the user asked. Matched anywhere in the opening prompt because
// these are generated with varying preambles.
var internalPromptPhrases = []string{
	"generate a title that will help the user recognize",
	"return json with exactly one key: title",
	"please write a 5-10 word title for the following conversation",
	"summarize this conversation in",
}

// isSyntheticPrompt reports whether a recorded user turn was produced by the
// tooling rather than typed by the user. An empty turn counts: there is nothing
// to justify treating it as a prompt.
func isSyntheticPrompt(text string) bool {
	trimmed := strings.TrimSpace(text)
	if trimmed == "" {
		return true
	}
	for _, prefix := range syntheticPromptPrefixes {
		if strings.HasPrefix(trimmed, prefix) {
			return true
		}
	}
	lower := strings.ToLower(trimmed)
	for _, phrase := range internalPromptPhrases {
		if strings.Contains(lower, phrase) {
			return true
		}
	}
	return false
}
