package sessionimport

import (
	"context"
	"path/filepath"
	"strings"
	"testing"
	"unicode/utf8"
)

func TestSyntheticPromptsAreNotHumanTurns(t *testing.T) {
	synthetic := []string{
		"<local-command-caveat>Caveat: the messages below were generated…</local-command-caveat>",
		"<command-name>/model</command-name>",
		"<system-reminder>Background context</system-reminder>",
		"Caveat: The messages below were generated by the user while running local commands.",
		// Codex echoes shell input and output into the conversation.
		"<bash-input>ls</bash-input>",
		"<bash-output>total 0</bash-output>",
		"<user_instructions>be terse</user_instructions>",
		// The tooling asking the agent to title the thread is not a user prompt.
		"Generate a title that will help the user recognize this thread weeks later.\nReturn JSON with exactly one key: title.",
		"   ",
	}
	for _, text := range synthetic {
		if !isSyntheticPrompt(text) {
			t.Errorf("should be treated as injected, not typed: %q", text)
		}
	}
	for _, text := range []string{"fix the flaky test", "why does <command-name> show up?"} {
		if isSyntheticPrompt(text) {
			t.Errorf("a real prompt was mistaken for injected text: %q", text)
		}
	}
}

func TestNormalizeTitleTruncatesOnRunes(t *testing.T) {
	// A multi-byte title truncated by bytes would split a rune and render as a
	// replacement character in the sidebar.
	got := normalizeTitle(strings.Repeat("é", maxTitleLen*2))
	if !utf8.ValidString(got) {
		t.Errorf("truncation split a multi-byte rune: %q", got)
	}
}

func TestCodexAdoptsNewestSegmentDespiteALaterIndexTimestamp(t *testing.T) {
	root := t.TempDir()
	codexHome := filepath.Join(root, ".codex")
	day := filepath.Join(codexHome, "sessions", "2026", "08", "21")

	writeFile(t, filepath.Join(day, "rollout-2026-08-21T09-00-00-019fbaf8-67a4-79b2-aa80-01283063aab8.jsonl"), codexRollout)
	writeFile(t, filepath.Join(day, "rollout-2026-08-21T09-30-00-019fbfff-67a4-79b2-aa80-01283063aab8.jsonl"), codexRolloutResume)
	// The index claims activity well after both segments.
	writeFile(t, filepath.Join(codexHome, "session_index.jsonl"),
		`{"id":"019fbaf8-67a4-79b2-aa80-01283063aab8","thread_name":"Valence health endpoint","updated_at":"2026-08-22T12:00:00.000Z"}`+"\n")

	svc := NewService(nil, NewCodexSourceAt(codexHome, true))
	got, err := svc.Discover(context.Background(), DiscoverOptions{})
	if err != nil {
		t.Fatalf("discover: %v", err)
	}
	if len(got) != 1 {
		t.Fatalf("want one conversation, got %d", len(got))
	}
	if !strings.HasSuffix(got[0].TranscriptPath, "019fbfff-67a4-79b2-aa80-01283063aab8.jsonl") {
		t.Errorf("the newest segment should represent the conversation, got %s", got[0].TranscriptPath)
	}
	// Renaming in the index must not make an inactive conversation eligible.
	if !got[0].LastActivity.Equal(parseTime("2026-08-21T09:30:05.000Z")) {
		t.Errorf("transcript activity should determine recency, got %s", got[0].LastActivity)
	}
}

func TestUnderAnyRoot(t *testing.T) {
	if !underAnyRoot("/a/b/c", []string{"/a/b"}) {
		t.Error("a directory inside a root is under it")
	}
	if !underAnyRoot("/a/b", []string{"/a/b"}) {
		t.Error("a root is under itself")
	}
	if underAnyRoot("/a/bc", []string{"/a/b"}) {
		t.Error("a sibling sharing a name prefix is not inside the root")
	}
	if underAnyRoot("/a/b", nil) || underAnyRoot("", []string{"/a"}) {
		t.Error("empty inputs must not match")
	}
}
