/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellTerminalsRouteImport } from './routes/_shell.terminals'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellSessionsSessionIdRouteImport } from './routes/_shell.sessions.$sessionId'
import { Route as ShellProjectsProjectIdRouteImport } from './routes/_shell.projects.$projectId'
import { Route as ShellProjectsProjectIdWorkflowRouteImport } from './routes/_shell.projects.$projectId_.workflow'
import { Route as ShellProjectsProjectIdSettingsRouteImport } from './routes/_shell.projects.$projectId_.settings'
import { Route as ShellProjectsProjectIdWorkflowRolesRouteImport } from './routes/_shell.projects.$projectId_.workflow.roles'
import { Route as ShellProjectsProjectIdWorkflowPlanIdRouteImport } from './routes/_shell.projects.$projectId_.workflow.$planId'
import { Route as ShellProjectsProjectIdSessionsSessionIdRouteImport } from './routes/_shell.projects.$projectId_.sessions.$sessionId'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTerminalsRoute = ShellTerminalsRouteImport.update({
  id: '/terminals',
  path: '/terminals',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSessionsSessionIdRoute = ShellSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProjectsProjectIdRoute = ShellProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProjectsProjectIdWorkflowRoute =
  ShellProjectsProjectIdWorkflowRouteImport.update({
    id: '/projects/$projectId_/workflow',
    path: '/projects/$projectId/workflow',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellProjectsProjectIdSettingsRoute =
  ShellProjectsProjectIdSettingsRouteImport.update({
    id: '/projects/$projectId_/settings',
    path: '/projects/$projectId/settings',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellProjectsProjectIdWorkflowRolesRoute =
  ShellProjectsProjectIdWorkflowRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => ShellProjectsProjectIdWorkflowRoute,
  } as any)
const ShellProjectsProjectIdWorkflowPlanIdRoute =
  ShellProjectsProjectIdWorkflowPlanIdRouteImport.update({
    id: '/$planId',
    path: '/$planId',
    getParentRoute: () => ShellProjectsProjectIdWorkflowRoute,
  } as any)
const ShellProjectsProjectIdSessionsSessionIdRoute =
  ShellProjectsProjectIdSessionsSessionIdRouteImport.update({
    id: '/projects/$projectId_/sessions/$sessionId',
    path: '/projects/$projectId/sessions/$sessionId',
    getParentRoute: () => ShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/settings': typeof ShellSettingsRoute
  '/terminals': typeof ShellTerminalsRoute
  '/projects/$projectId': typeof ShellProjectsProjectIdRoute
  '/sessions/$sessionId': typeof ShellSessionsSessionIdRoute
  '/projects/$projectId/settings': typeof ShellProjectsProjectIdSettingsRoute
  '/projects/$projectId/workflow': typeof ShellProjectsProjectIdWorkflowRouteWithChildren
  '/projects/$projectId/sessions/$sessionId': typeof ShellProjectsProjectIdSessionsSessionIdRoute
  '/projects/$projectId/workflow/$planId': typeof ShellProjectsProjectIdWorkflowPlanIdRoute
  '/projects/$projectId/workflow/roles': typeof ShellProjectsProjectIdWorkflowRolesRoute
}
export interface FileRoutesByTo {
  '/settings': typeof ShellSettingsRoute
  '/terminals': typeof ShellTerminalsRoute
  '/': typeof ShellIndexRoute
  '/projects/$projectId': typeof ShellProjectsProjectIdRoute
  '/sessions/$sessionId': typeof ShellSessionsSessionIdRoute
  '/projects/$projectId/settings': typeof ShellProjectsProjectIdSettingsRoute
  '/projects/$projectId/workflow': typeof ShellProjectsProjectIdWorkflowRouteWithChildren
  '/projects/$projectId/sessions/$sessionId': typeof ShellProjectsProjectIdSessionsSessionIdRoute
  '/projects/$projectId/workflow/$planId': typeof ShellProjectsProjectIdWorkflowPlanIdRoute
  '/projects/$projectId/workflow/roles': typeof ShellProjectsProjectIdWorkflowRolesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/terminals': typeof ShellTerminalsRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/projects/$projectId': typeof ShellProjectsProjectIdRoute
  '/_shell/sessions/$sessionId': typeof ShellSessionsSessionIdRoute
  '/_shell/projects/$projectId_/settings': typeof ShellProjectsProjectIdSettingsRoute
  '/_shell/projects/$projectId_/workflow': typeof ShellProjectsProjectIdWorkflowRouteWithChildren
  '/_shell/projects/$projectId_/sessions/$sessionId': typeof ShellProjectsProjectIdSessionsSessionIdRoute
  '/_shell/projects/$projectId_/workflow/$planId': typeof ShellProjectsProjectIdWorkflowPlanIdRoute
  '/_shell/projects/$projectId_/workflow/roles': typeof ShellProjectsProjectIdWorkflowRolesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/terminals'
    | '/projects/$projectId'
    | '/sessions/$sessionId'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/workflow'
    | '/projects/$projectId/sessions/$sessionId'
    | '/projects/$projectId/workflow/$planId'
    | '/projects/$projectId/workflow/roles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/terminals'
    | '/'
    | '/projects/$projectId'
    | '/sessions/$sessionId'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/workflow'
    | '/projects/$projectId/sessions/$sessionId'
    | '/projects/$projectId/workflow/$planId'
    | '/projects/$projectId/workflow/roles'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/settings'
    | '/_shell/terminals'
    | '/_shell/'
    | '/_shell/projects/$projectId'
    | '/_shell/sessions/$sessionId'
    | '/_shell/projects/$projectId_/settings'
    | '/_shell/projects/$projectId_/workflow'
    | '/_shell/projects/$projectId_/sessions/$sessionId'
    | '/_shell/projects/$projectId_/workflow/$planId'
    | '/_shell/projects/$projectId_/workflow/roles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/terminals': {
      id: '/_shell/terminals'
      path: '/terminals'
      fullPath: '/terminals'
      preLoaderRoute: typeof ShellTerminalsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/sessions/$sessionId': {
      id: '/_shell/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof ShellSessionsSessionIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects/$projectId': {
      id: '/_shell/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ShellProjectsProjectIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects/$projectId_/workflow': {
      id: '/_shell/projects/$projectId_/workflow'
      path: '/projects/$projectId/workflow'
      fullPath: '/projects/$projectId/workflow'
      preLoaderRoute: typeof ShellProjectsProjectIdWorkflowRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects/$projectId_/settings': {
      id: '/_shell/projects/$projectId_/settings'
      path: '/projects/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ShellProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects/$projectId_/workflow/roles': {
      id: '/_shell/projects/$projectId_/workflow/roles'
      path: '/roles'
      fullPath: '/projects/$projectId/workflow/roles'
      preLoaderRoute: typeof ShellProjectsProjectIdWorkflowRolesRouteImport
      parentRoute: typeof ShellProjectsProjectIdWorkflowRoute
    }
    '/_shell/projects/$projectId_/workflow/$planId': {
      id: '/_shell/projects/$projectId_/workflow/$planId'
      path: '/$planId'
      fullPath: '/projects/$projectId/workflow/$planId'
      preLoaderRoute: typeof ShellProjectsProjectIdWorkflowPlanIdRouteImport
      parentRoute: typeof ShellProjectsProjectIdWorkflowRoute
    }
    '/_shell/projects/$projectId_/sessions/$sessionId': {
      id: '/_shell/projects/$projectId_/sessions/$sessionId'
      path: '/projects/$projectId/sessions/$sessionId'
      fullPath: '/projects/$projectId/sessions/$sessionId'
      preLoaderRoute: typeof ShellProjectsProjectIdSessionsSessionIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellProjectsProjectIdWorkflowRouteChildren {
  ShellProjectsProjectIdWorkflowPlanIdRoute: typeof ShellProjectsProjectIdWorkflowPlanIdRoute
  ShellProjectsProjectIdWorkflowRolesRoute: typeof ShellProjectsProjectIdWorkflowRolesRoute
}

const ShellProjectsProjectIdWorkflowRouteChildren: ShellProjectsProjectIdWorkflowRouteChildren =
  {
    ShellProjectsProjectIdWorkflowPlanIdRoute:
      ShellProjectsProjectIdWorkflowPlanIdRoute,
    ShellProjectsProjectIdWorkflowRolesRoute:
      ShellProjectsProjectIdWorkflowRolesRoute,
  }

const ShellProjectsProjectIdWorkflowRouteWithChildren =
  ShellProjectsProjectIdWorkflowRoute._addFileChildren(
    ShellProjectsProjectIdWorkflowRouteChildren,
  )

interface ShellRouteChildren {
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellTerminalsRoute: typeof ShellTerminalsRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellProjectsProjectIdRoute: typeof ShellProjectsProjectIdRoute
  ShellSessionsSessionIdRoute: typeof ShellSessionsSessionIdRoute
  ShellProjectsProjectIdSettingsRoute: typeof ShellProjectsProjectIdSettingsRoute
  ShellProjectsProjectIdWorkflowRoute: typeof ShellProjectsProjectIdWorkflowRouteWithChildren
  ShellProjectsProjectIdSessionsSessionIdRoute: typeof ShellProjectsProjectIdSessionsSessionIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellSettingsRoute: ShellSettingsRoute,
  ShellTerminalsRoute: ShellTerminalsRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellProjectsProjectIdRoute: ShellProjectsProjectIdRoute,
  ShellSessionsSessionIdRoute: ShellSessionsSessionIdRoute,
  ShellProjectsProjectIdSettingsRoute: ShellProjectsProjectIdSettingsRoute,
  ShellProjectsProjectIdWorkflowRoute:
    ShellProjectsProjectIdWorkflowRouteWithChildren,
  ShellProjectsProjectIdSessionsSessionIdRoute:
    ShellProjectsProjectIdSessionsSessionIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
